# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          pg_isready

      - name: Create additional user
        run: |
          sudo -u postgres psql --command="CREATE USER testuser PASSWORD 'password'" --command="\du"

      - name: Create additional database
        run: |
          sudo -u postgres createdb TestDatabase --owner=testuser 
          PGPASSWORD=password

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get Dependencies
        run: cd ./src && pwd && go get ...

      - name: Build
        run: cd ./src && pwd && go build -v .

      - name: Test
        run: cd ./src && pwd && go test -cover ./...
        env:
          DATABASE_CONNECTION_STRING_TEST: "host=localhost port=5432 user=testuser password=password dbname=TestDatabase sslmode=disable"
          DATABASE_CONNECTION_STRING_ERROR: "host=localhost port=5432 user=someuserthatdoesntexist password=password dbname=TestDatabase sslmode=disable"
          GITHUB_ACTION: "true"
