# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          pg_isready

      - name: Create additional user
        run: |
          sudo -u postgres psql --command="CREATE USER test PASSWORD 'password'" --command="\du"
          sudo -u postgres psql --command="ALTER USER test WITH SUPERUSER"

      - name: Create additional database
        run: |
          sudo -u postgres createdb lenslocked_test --owner=test
          PGPASSWORD=password psql --username=test --password=password --host=localhost --list lenslocked_test

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get Dependencies
        run: cd ./src && pwd && go get ...

      - name: Build
        run: cd ./src && pwd && go build -v .

      - name: Test
        run: cd ./src && pwd && go test -cover ./...
